<#
.SYNOPSIS
  Interactive wizard for creating backend/.env (PowerShell).

.DESCRIPTION
  Use case: scripts/dev.ps1 works out of the box in test mode (no .env
  needed). Run this wizard when you want to use scripts/dev.ps1 --real -
  real Google OAuth sign-in instead of the dummy test login.

  What it does:
    - Walks through each variable from backend/.env.example, with defaults
    - Generates a strong 64-hex-char JWT_SECRET if you press 'g'
    - Validates required fields and URL formats inline
    - Refuses to overwrite an existing backend/.env without confirmation
    - Detects Ctrl+C via trap and exits cleanly instead of writing a
      malformed file
    - Writes a clean file with a '# Generated by ...' header
    - JWT_SECRET is generated via RandomNumberGenerator.Create() (the
      .NET equivalent of crypto.randomBytes; .NET Framework via PS 5.1
      and .NET 6+ via PS 7 both expose it identically).

  KEEP IN SYNC with scripts/env-wizard.sh and the (legacy) env-wizard.js.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$Root = Resolve-Path (Join-Path $PSScriptRoot '..')
$Backend = Join-Path $Root 'backend'
$EnvPath = Join-Path $Backend '.env'
$ExamplePath = Join-Path $Backend '.env.example'

$MaxAttempts = 3

# Ctrl+C / Ctrl+D aborts cleanly. PS doesn't have a separate 'EOF on
# stdin' signal like Node's rl.on('close'), but pressing Ctrl+D on a
# Read-Host line raises an exception which the same trap catches.
trap {
    Write-Host ''
    Write-Host '  Aborted. No file was written.' -ForegroundColor Yellow
    exit 130
}

function Get-CwdRelative {
    param([Parameter(Mandatory)][string]$Full)
    $cwd = (Get-Location).Path
    if ($Full.Length -gt $cwd.Length -and
        $Full.Substring(0, $cwd.Length).Equals($cwd, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $Full.Substring($cwd.Length).TrimStart('\', '/')
    }
    return $Full
}

function Test-ValidUrl {
    # .NET Uri throws on malformed input. We accept only http(s).
    param([Parameter(Mandatory)][string]$Url)
    try {
        $u = New-Object System.Uri $Url
        return ($u.Scheme -eq 'http' -or $u.Scheme -eq 'https')
    } catch {
        return $false
    }
}

function Test-ValidPort {
    param([Parameter(Mandatory)][string]$Port)
    if ($Port -notmatch '^\d+$') { return $false }
    $n = [int]$Port
    return ($n -gt 0 -and $n -lt 65536)
}

function New-JwtSecret {
    # Crypto-strong 64 hex chars (32 bytes). .NET maps the underlying OS
    # CSPRNG (BCryptGenRandom on Windows, /dev/urandom on Unix) so this
    # is identical security-wise to crypto.randomBytes(32).toString('hex').
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object 'System.Byte[]' 32
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return (-join ($bytes | ForEach-Object { $_.ToString('x2') }))
}

function Ask {
    # Prompts the user with a default fallback + validator scriptblock.
    # Returns whatever the user typed (after MAX_ATTEMPTS failed
    # validations, returns the last bad value rather than hanging on a
    # closed stdin - mirrors JS MAX_ATTEMPTS bail behaviour).
    param(
        [Parameter(Mandatory)][string]$Question,
        [string]$Default = '',
        [scriptblock]$Validator = $null
    )

    for ($i = 0; $i -lt $MaxAttempts; $i++) {
        $prompt = if ($Default) { "$Question ($Default): " } else { "$Question: " }
        Write-Host -NoNewline $prompt
        $answer = Read-Host
        if ([string]::IsNullOrWhiteSpace($answer)) {
            $value = $Default
        } else {
            $value = $answer.Trim()
        }

        if ($null -ne $Validator) {
            $err = & $Validator $value
            if ($err) {
                Write-Host "  ✗ $err" -ForegroundColor Red
                if ($i + 1 -ge $MaxAttempts) {
                    Write-Host "  (gave up after $MaxAttempts attempts; re-run to retry)" -ForegroundColor Yellow
                    return $value
                }
                continue
            }
        }
        return $value
    }
    return $null
}

# ----------------------------- main flow ---------------------------------

Write-Host '▶ IrMeetingApp .env wizard' -ForegroundColor Cyan
Write-Host ''
Write-Host '  Creates backend/.env so you can run scripts/dev.ps1 --real'
Write-Host '  (real Google OAuth, test routes disabled).'
Write-Host ''
Write-Host '  For day-to-day dev you can skip this entirely - scripts/dev.ps1'
Write-Host '  works in test mode without any .env file.'
Write-Host ''

if (-not (Test-Path $ExamplePath)) {
    Write-Host '  ✗ backend/.env.example not found; aborting.' -ForegroundColor Red
    exit 1
}

# Overwrite guard - never destroy a real .env silently.
if (Test-Path $EnvPath) {
    Write-Host ('  · ' + (Get-CwdRelative $EnvPath) + ' already exists.') -ForegroundColor Yellow
    $overwrite = Ask '  Overwrite? (y/N)' 'N' { param($v)
        if ($v -match '^(y|yes|n|no)$') { return $null } else { return 'answer with y or n' }
    }
    if ($overwrite -notmatch '^y(es)?$') {
        Write-Host '  Aborted. Existing .env left untouched.' -ForegroundColor Yellow
        exit 0
    }
    Write-Host ''
    Write-Host '  Heads-up: if you regenerate JWT_SECRET, every existing user' -ForegroundColor Yellow
    Write-Host '  session becomes invalid (token signatures change).' -ForegroundColor Yellow
    Write-Host ''
}

$out = [ordered]@{}

# --- JWT_SECRET first, with a generator shortcut -------------------------
$secretMode = Ask 'JWT_SECRET (required, min 32 chars): (g)enerate or (e)nter' 'g' { param($v)
    if ($v -match '^(g|e)$') { return $null } else { return 'press g to generate, e to enter your own' }
}

if ($secretMode -match '^g') {
    $out['JWT_SECRET'] = New-JwtSecret
    # Show only the prefix so the secret isn't echoed in full through
    # the terminal scrollback.
    Write-Host ('  ✓ Generated JWT_SECRET (' + $out['JWT_SECRET'].Length + ' chars): ' + $out['JWT_SECRET'].Substring(0, 8) + '…') -ForegroundColor Green
} else {
    $out['JWT_SECRET'] = Ask '  Enter your JWT_SECRET (≥ 32 chars)' '' { param($v)
        if ($v.Length -ge 32) { return $null } else { return "must be at least 32 characters (got $($v.Length))" }
    }
}

# --- The rest, with defaulted sensible values ----------------------------
$out['NODE_ENV'] = Ask 'NODE_ENV' 'development' { param($v)
    if ($v -match '^(development|production|test)$') { return $null } else { return 'must be development | production | test' }
}

$out['PORT'] = Ask 'PORT' '3001' { param($v)
    if (Test-ValidPort $v) { return $null } else { return 'must be a TCP port number (1-65535)' }
}

# Default HOST to 127.0.0.1 to dodge the well-known Windows IPv4/IPv6
# gotcha (Node 17+ resolves localhost -> ::1 while server binds IPv4).
# 127.0.0.1 works identically on macOS/Linux.
Write-Host '  Tip: HOST=127.0.0.1 avoids a Windows IPv4/IPv6 gotcha; works on macOS/Linux too.' -ForegroundColor DarkGray
$out['HOST'] = Ask 'HOST' '127.0.0.1'

Write-Host ''
Write-Host '  Google OAuth credentials (create at https://console.cloud.google.com/'
Write-Host '  -> APIs & Services -> Credentials -> Create OAuth client ID -> Web app).'
Write-Host '  Authorized redirect URI must match whatever you give for GOOGLE_REDIRECT_URI below.'
Write-Host ''

$out['GOOGLE_CLIENT_ID'] = Ask 'GOOGLE_CLIENT_ID (required)' '' { param($v)
    if ($v.Length -ge 5) { return $null } else { return 'required' }
}
$out['GOOGLE_CLIENT_SECRET'] = Ask 'GOOGLE_CLIENT_SECRET (required)' '' { param($v)
    if ($v.Length -ge 5) { return $null } else { return 'required' }
}

$out['GOOGLE_REDIRECT_URI'] = Ask 'GOOGLE_REDIRECT_URI' 'http://localhost:3001/api/auth/google/callback' { param($v)
    if (Test-ValidUrl $v) { return $null } else { return 'must be a valid http(s) URL (e.g. https://example.com/callback)' }
}
$out['FRONTEND_URL'] = Ask 'FRONTEND_URL' 'http://localhost:5173' { param($v)
    if (Test-ValidUrl $v) { return $null } else { return 'must be a valid http(s) URL' }
}

$out['JWT_EXPIRATION'] = Ask 'JWT_EXPIRATION (access token TTL)' '15m'
$out['REFRESH_TOKEN_EXPIRATION'] = Ask 'REFRESH_TOKEN_EXPIRATION (refresh token TTL)' '30d'
$out['DATABASE_PATH'] = Ask 'DATABASE_PATH' './data/irmeeting.db'

# --- Post-loop sanity check ----------------------------------------------
# MAX_ATTEMPTS lets each field bail with whatever was last typed. If a
# required field ended up empty, abort BEFORE writing - the backend
# would crash on boot anyway, and silent failure here is a worse UX
# than a clear abort with a "re-run the wizard" hint.
$required = @{
    'GOOGLE_CLIENT_ID'     = $out['GOOGLE_CLIENT_ID']
    'GOOGLE_CLIENT_SECRET' = $out['GOOGLE_CLIENT_SECRET']
    'JWT_SECRET'           = $out['JWT_SECRET']
}
$missing = @($required.Keys | Where-Object { [string]::IsNullOrEmpty($required[$_]) })
if ($missing.Count -gt 0) {
    Write-Host ''
    Write-Host ('  ✗ Required fields missing: ' + ($missing -join ', ')) -ForegroundColor Red
    Write-Host '    Re-run: scripts/env-wizard.ps1' -ForegroundColor Yellow
    exit 1
}

# --- Compose & write -----------------------------------------------------
# Backtick-escape every literal backtick inside the double-quoted heredoc
# (PowerShell uses backtick as the line-continuation / escape char).
$header = "# Generated by ``scripts/env-wizard.ps1`` on $([DateTime]::UtcNow.ToString('o'))`n# Edit freely; changes take effect on the next ``scripts/dev.ps1 --real``."

$body = @(
    '# Server'
    "NODE_ENV=$($out['NODE_ENV'])"
    "PORT=$($out['PORT'])"
    "HOST=$($out['HOST'])"
    ''
    '# Google OAuth'
    "GOOGLE_CLIENT_ID=$($out['GOOGLE_CLIENT_ID'])"
    "GOOGLE_CLIENT_SECRET=$($out['GOOGLE_CLIENT_SECRET'])"
    "GOOGLE_REDIRECT_URI=$($out['GOOGLE_REDIRECT_URI'])"
    ''
    '# JWT'
    "JWT_SECRET=$($out['JWT_SECRET'])"
    "JWT_EXPIRATION=$($out['JWT_EXPIRATION'])"
    "REFRESH_TOKEN_EXPIRATION=$($out['REFRESH_TOKEN_EXPIRATION'])"
    ''
    '# Frontend URL (for CORS and redirects)'
    "FRONTEND_URL=$($out['FRONTEND_URL'])"
    ''
    '# Database'
    "DATABASE_PATH=$($out['DATABASE_PATH'])"
    ''
) -join "`n"

# .NET's File.WriteAllText doesn't expose POSIX mode bits; Windows has
# no permission model anyway. The bash version tries chmod 600 + falls
# back gracefully - we mirror that here by simply writing the file.
# (If the backend has the file locked we still surface the unlock
# guidance via the inherited exception handler.)
try {
    [System.IO.File]::WriteAllText($EnvPath, $header + "`n" + $body)
    Write-Host ''
    $lineCount = ($header + "`n" + $body).Split("`n").Length - 1
    Write-Host ('✓ Wrote ' + $lineCount + ' lines to ' + (Get-CwdRelative $EnvPath)) -ForegroundColor Green
    Write-Host '  (Windows has no POSIX mode bits; .env inherits the parent ACL.)' -ForegroundColor DarkGray
    Write-Host ''
    Write-Host '  Next:' -ForegroundColor Cyan
    Write-Host '    scripts/dev.ps1 --real    # start backend + frontend with these credentials' -ForegroundColor Cyan
    Write-Host '    scripts/dev.ps1          # day-to-day dev (test mode, ignores this file)' -ForegroundColor Cyan
}
catch {
    Write-Host ('  ✗ failed to write ' + (Get-CwdRelative $EnvPath) + ': ' + $_.Exception.Message) -ForegroundColor Red
    exit 1
}
