#!/usr/bin/env node
/**
 * Interactive wizard for creating backend/.env.
 *
 * Use case: `npm run dev` works out of the box in test mode (no .env
 * needed). Run this wizard when you want to use `npm run dev:real` —
 * real Google OAuth sign-in instead of the dummy test login.
 *
 * What it does:
 *   - Walks through each variable from backend/.env.example, with defaults.
 *   - Generates a strong 64-hex-char JWT_SECRET if you press `g`.
 *   - Validates required fields and URL formats inline.
 *   - Refuses to overwrite an existing backend/.env without confirmation.
 *   - Detects stdin close (Ctrl+D / piped EOF) and exits cleanly instead
 *     of hanging or silently writing an invalid file.
 *   - Writes a clean file with a `# Generated by …` header.
 *
 * Pure Node (readline + crypto), no extra deps.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const BACKEND = path.resolve(__dirname, '..', 'backend');
const ENV_PATH = path.join(BACKEND, '.env');
const EXAMPLE_PATH = path.join(BACKEND, '.env.example');

const MAX_ATTEMPTS = 3; // per-field, avoids infinite recursion on bad input
let stdinClosed = false;

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

// Clean up gracefully on Ctrl+C.
rl.on('SIGINT', () => {
  console.log('\n  Aborted. No file was written.');
  rl.close();
  process.exit(130);
});

// Detect Ctrl+D / piped EOF: stop the wizard rather than hang on the
// next prompt or silently write a malformed file.
rl.on('close', () => {
  stdinClosed = true;
});

/**
 * Prompt the user. `defaultValue` shown in parentheses and used when the
 * input is empty. `validator` returns null on success or a string error
 * message on failure. On failure we re-ask up to MAX_ATTEMPTS times so
 * stdin being closed (Ctrl+D) can't cascade into infinite re-prompts.
 */
function ask(question, defaultValue, validator, attempt = 0) {
  return new Promise((resolve) => {
    if (stdinClosed) {
      console.log(`\n  ! stdin closed before "${question}" was answered — aborting.`);
      process.exit(130);
    }

    const prompt = defaultValue ? `${question} (${defaultValue}): ` : `${question}: `;
    rl.question(prompt, (answer) => {
      const raw = (answer ?? '').trim();
      const value = raw === '' ? (defaultValue ?? '') : raw;

      if (typeof validator === 'function') {
        const err = validator(value);
        if (err) {
          console.log(`  ✗ ${err}`);
          if (attempt + 1 >= MAX_ATTEMPTS) {
            console.log(`  (gave up after ${MAX_ATTEMPTS} attempts; re-run \`npm run env:wizard\` to retry)`);
            resolve(value);
            return;
          }
          return ask(question, defaultValue, validator, attempt + 1).then(resolve);
        }
      }
      resolve(value);
    });
  });
}

(async () => {
  console.log('▶ IrMeetingApp .env wizard');
  console.log('');
  console.log('  Creates backend/.env so you can run `npm run dev:real`');
  console.log('  (real Google OAuth, test routes disabled).');
  console.log('');
  console.log('  For day-to-day dev you can skip this entirely — `npm run dev`');
  console.log('  works in test mode without any .env file.');
  console.log('');

  if (!fs.existsSync(EXAMPLE_PATH)) {
    console.error(`✗ ${path.relative(process.cwd(), EXAMPLE_PATH)} not found; aborting.`);
    process.exit(1);
  }

  // Overwrite guard — never destroy a real .env silently.
  if (fs.existsSync(ENV_PATH)) {
    console.log(`  · ${path.relative(process.cwd(), ENV_PATH)} already exists.`);
    const overwrite = await ask('  Overwrite? (y/N)', 'N', (v) =>
      /^(y|yes|n|no)$/i.test(v) ? null : 'answer with y or n',
    );
    if (!/^y(es)?$/i.test(overwrite)) {
      console.log('  Aborted. Existing .env left untouched.');
      rl.close();
      return;
    }
    console.log('');
    console.log('  Heads-up: if you regenerate JWT_SECRET, every existing user');
    console.log('  session becomes invalid (token signatures change).');
    console.log('');
  }

  const out = {};

  // --- JWT_SECRET first, with a generator shortcut ----------------------
  const secretMode = await ask(
    'JWT_SECRET (required, min 32 chars): (g)enerate or (e)nter',
    'g',
    (v) => (/^(g|e)$/i.test(v) ? null : 'press g to generate, e to enter your own'),
  );

  if (/^g/i.test(secretMode)) {
    // 64 hex chars — easily satisfies backend's min-32-chars constraint and
    // is cryptographically strong. Show only the prefix so the secret isn't
    // echoed through the terminal after generation.
    out.JWT_SECRET = crypto.randomBytes(32).toString('hex');
    console.log(`  ✓ Generated JWT_SECRET (${out.JWT_SECRET.length} chars): ${out.JWT_SECRET.slice(0, 8)}…`);
  } else {
    out.JWT_SECRET = await ask(
      '  Enter your JWT_SECRET (≥ 32 chars)',
      undefined,
      (v) => (v.length >= 32 ? null : `must be at least 32 characters (got ${v.length})`),
    );
  }

  // --- The rest, with defaulted sensible values ------------------------
  out.NODE_ENV = await ask(
    'NODE_ENV',
    'development',
    (v) => (/^(development|production|test)$/.test(v) ? null : 'must be development | production | test'),
  );

  out.PORT = await ask('PORT', '3001', (v) =>
    /^\d+$/.test(v) && +v > 0 && +v < 65536 ? null : 'must be a TCP port number (1–65535)',
  );

  // Default HOST to 127.0.0.1 to dodge the well-known Windows IPv4/IPv6
  // gotcha (Node 17+ resolves `localhost` → IPv6 ::1 while the server
  // binds IPv4). 127.0.0.1 works identically on macOS/Linux/macOS.
  console.log('  Tip: HOST=127.0.0.1 avoids a Windows IPv4/IPv6 gotcha; works on macOS/Linux too.');
  out.HOST = await ask('HOST', '127.0.0.1');

  console.log('');
  console.log('  Google OAuth credentials (create at https://console.cloud.google.com/');
  console.log('  → APIs & Services → Credentials → Create OAuth client ID → Web app).');
  console.log('  Authorized redirect URI must match whatever you give for GOOGLE_REDIRECT_URI below.');
  console.log('');

  out.GOOGLE_CLIENT_ID = await ask(
    'GOOGLE_CLIENT_ID (required)',
    undefined,
    (v) => (v.length >= 5 ? null : 'required'),
  );
  out.GOOGLE_CLIENT_SECRET = await ask(
    'GOOGLE_CLIENT_SECRET (required)',
    undefined,
    (v) => (v.length >= 5 ? null : 'required'),
  );

  const validateUrl = (v) => {
    try {
      const u = new URL(v);
      return u.protocol === 'http:' || u.protocol === 'https:'
        ? null
        : 'must be an http(s) URL';
    } catch {
      return 'must be a valid URL (e.g. https://example.com/callback)';
    }
  };

  out.GOOGLE_REDIRECT_URI = await ask(
    'GOOGLE_REDIRECT_URI',
    'http://localhost:3001/api/auth/google/callback',
    validateUrl,
  );
  out.FRONTEND_URL = await ask('FRONTEND_URL', 'http://localhost:5173', validateUrl);

  out.JWT_EXPIRATION = await ask('JWT_EXPIRATION (access token TTL)', '15m');
  out.REFRESH_TOKEN_EXPIRATION = await ask('REFRESH_TOKEN_EXPIRATION (refresh token TTL)', '30d');
  out.DATABASE_PATH = await ask('DATABASE_PATH', './data/irmeeting.db');

  // --- Post-loop sanity check -------------------------------------------
  // MAX_ATTEMPTS lets each field bail with whatever was last typed.
  // If a required field ended up empty, abort BEFORE writing — the backend
  // would crash on boot anyway, and silent failure here is a worse UX
  // than a clear abort with a "re-run the wizard" hint.
  const required = {
    GOOGLE_CLIENT_ID: out.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: out.GOOGLE_CLIENT_SECRET,
    JWT_SECRET: out.JWT_SECRET,
  };
  const missing = Object.entries(required)
    .filter(([, v]) => !v)
    .map(([k]) => k);
  if (missing.length > 0) {
    console.log('');
    console.log(`  ✗ Required fields missing: ${missing.join(', ')}`);
    console.log(`    Re-run: npm run env:wizard`);
    rl.close();
    process.exit(1);
  }

  // --- Compose & write ---------------------------------------------------
  const header = `# Generated by \`npm run env:wizard\` on ${new Date().toISOString()}\n# Edit freely; changes take effect on the next \`npm run dev:real\`.\n`;
  const body = [
    '# Server',
    `NODE_ENV=${out.NODE_ENV}`,
    `PORT=${out.PORT}`,
    `HOST=${out.HOST}`,
    '',
    '# Google OAuth',
    `GOOGLE_CLIENT_ID=${out.GOOGLE_CLIENT_ID}`,
    `GOOGLE_CLIENT_SECRET=${out.GOOGLE_CLIENT_SECRET}`,
    `GOOGLE_REDIRECT_URI=${out.GOOGLE_REDIRECT_URI}`,
    '',
    '# JWT',
    `JWT_SECRET=${out.JWT_SECRET}`,
    `JWT_EXPIRATION=${out.JWT_EXPIRATION}`,
    `REFRESH_TOKEN_EXPIRATION=${out.REFRESH_TOKEN_EXPIRATION}`,
    '',
    '# Frontend URL (for CORS and redirects)',
    `FRONTEND_URL=${out.FRONTEND_URL}`,
    '',
    '# Database',
    `DATABASE_PATH=${out.DATABASE_PATH}`,
    '',
  ].join('\n');

  // .env contains secrets — try for 0600 (owner-only). Windows ignores
  // the mode option silently and has no permission model anyway, so we
  // fall back gracefully there. If the backend has the file locked,
  // writeFileSync throws EBUSY; on Windows we retry without mode.
  let wrotePerms = false;
  try {
    fs.writeFileSync(ENV_PATH, header + body, { mode: 0o600 });
    wrotePerms = true;
  } catch (err) {
    if (err && err.code === 'EBUSY') {
      console.warn(`  ⚠ ${err.code} — backend may have the file locked. Retrying without permission hint.`);
      fs.writeFileSync(ENV_PATH, header + body);
    } else {
      throw err;
    }
  }

  // Header is 2 lines + body has trailing newline (one extra empty line).
  // Count the number of \n + 1 to subtract the trailing-newline artifact.
  const lineCount = (header + body).split('\n').length - 1;
  console.log('');
  console.log(`✓ Wrote ${lineCount} lines to ${path.relative(process.cwd(), ENV_PATH)}`);
  if (wrotePerms) {
    console.log('  File permissions set to 0600 (owner-only).');
  } else {
    console.log('  ⚠ Could not set 0600 permissions (likely Windows or file was locked).');
  }
  console.log('');
  console.log('  Next:');
  console.log('    npm run dev:real    # start backend + frontend with these credentials');
  console.log('    npm run dev         # day-to-day dev (test mode, ignores this file)');

  rl.close();
})().catch((err) => {
  console.error('✗ Wizard failed:', err && err.message ? err.message : err);
  try { rl.close(); } catch { /* already closed */ }
  process.exit(1);
});
